global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'company-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['company-service:8082']

  - job_name: 'job-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job-service:8083']

  - job_name: 'resume-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resume-service:8084']

  - job_name: 'file-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['file-service:8085']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']

